workflows:
  android-workflow:
    name: Android Workflow

    environment:
      java: 17

    scripts:
      - npm install
      - npm run build
      - npm install @capacitor/core @capacitor/cli @capacitor/android
      - npx cap sync android
      - cd android && chmod +x gradlew
      - cd android && ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
