workflows:
  android-workflow:
    name: Android Workflow

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

    scripts:
      - npm install
      - npm run build
      - npm install @capacitor/core @capacitor/cli @capacitor/android
      - npx cap sync android
      - cd android && chmod +x gradlew
      - cd android && ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
